title: Práctica 1 - Taller Transversal I
email: contacto@ejemplo.com

description: >-
  Página web realizada como práctica 1 de la asignatura Taller Transversal I.
  Proyecto realizado con Jekyll y GitHub Pages.

baseurl: "/Pr1Ej3TT1"
url: "https://caortio.github.io"

github_username: caortio

theme: jekyll-theme-cayman

plugins:
  - jekyll-feed
  - jekyll-seo-tag
