title: Página creada en la práctica 1 de TT1
email: email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Página web estática creada en la práctica 1 de la asignatura Taller Transversal I.
baseurl: "/Pr1Ej3TT1"
url: "" 

theme: minima
plugins:
  - jekyll-feed
